name: Flutter CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: development
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: SpicyPizza/create-envfile@v1
        with:
          envkey_API_KEY_ANDROID: ${{ secrets.API_KEY_ANDROID}}
          envkey_APP_ID_ANDROID: ${{ secrets.APP_ID_ANDROID}}
          envkey_APP_KEY_IOS: ${{ secrets.APP_KEY_IOS}}
          envkey_APP_ID_IOS: ${{ secrets.APP_ID_IOS}}
          envkey_MESSAGING_SENDER_ID: ${{ secrets.MESSAGING_SENDER_ID}}
          envkey_PROJECT_ID: ${{ secrets.PROJECT_ID}}
          envkey_STORAGE_BUCKET: ${{ secrets.STORAGE_BUCKET}}
          envkey_IOS_CLIENT_ID: ${{ secrets.IOS_CLIENT_ID}}
          envkey_IOS_BUNDLED: ${{ secrets.IOS_BUNDLED}}
      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
      - run: flutter pub get
      - run: flutter format .
      - run: flutter clean
#      - run: flutter analyze .
      - run: flutter build apk
      - uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk